DROP TABLE IF EXISTS "blog_user" CASCADE;
DROP TABLE IF EXISTS "post";
CREATE TABLE "blog_user" ("id" SERIAL PRIMARY KEY,"username" TEXT UNIQUE NOT NULL,"password" TEXT NOT NULL);
CREATE TABLE "post" ("id" SERIAL PRIMARY KEY,"author_id" INTEGER NOT NULL,"created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"title" TEXT NOT NULL,"body" TEXT NOT NULL,FOREIGN KEY ("author_id") REFERENCES "blog_user" ("id"));
