---

  - name: Check if ansible works on the web server
    ping:

  - name: Add gitlab private key
    copy:
      src: gitlab_id_rsa
      dest: /home/vagrant/.ssh/id_rsa
      owner: vagrant
      group: vagrant
      mode: 0600

  - name: Create the www directory
    file:
      path: /var/www
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Create the ncg-devops directory
    file:
      path: /var/www/ncg-devops
      state: directory
      mode: 0755
      owner: vagrant
      group: vagrant


  - name: Install git
    yum:
      name: git
      state: latest

  - name: Clone the git repo
    git:
      repo: 'git@gitlab.eng.vmware.com:abilgi/ncg-devops-hands-on.git'
      dest: '/var/www/ncg-devops'
      ssh_opts: "-o StrictHostKeyChecking=no"
    become: True
    become_user: vagrant