---

- name: Configure the database server
  hosts: dbservers
  vars_files:
    - roles/database/vars/main.yml
  roles:
    - database
  become: True

- name: Configure the web server
  hosts: webservers
  roles:
    - web
  become: True
